name: Test GitHub Pages on Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        uses: actions/jekyll-build-pages@v1

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site/
          preview-branch: test-pull-request-pages
